### PR TITLE
rename package to @metamask/react-native-webview

### PR DESCRIPTION
**Pull request by legobeat**
Prepare for publish as `@metamask/react-native-webview`

### CODE REVIEW

**Comment by jpcloureiro** [comment]
@legobeat yes, `main` is the correct branch to merge into

I'm looking into the iOS pod setup failures

**Comment by jpcloureiro** [comment]
Podspec filename must match its name attribute

Here's the commit with the changes to get pods installed
https://github.com/MetaMask/react-native-webview-mm/commit/7860fbd09abf29f7a77f0c4125c1e7f9ed71997b

**Comment by legobeat** [comment]
> Podspec filename must match its name attribute
> 
> Here's the commit with the changes to get pods to install [7860fbd](https://github.com/MetaMask/react-native-webview-mm/commit/7860fbd09abf29f7a77f0c4125c1e7f9ed71997b)

@jpcloureiro Thanks! Merged: d05d52564b26141e139bd1dd70fb25f6f102fcf2

**Comment by legobeat** [comment]
[Failing](https://github.com/MetaMask/react-native-webview-mm/actions/runs/8946301007/job/24576718364?pr=15) Detox CI Tests:
```
Error: Unable to find Node version '14' for platform darwin and architecture arm64.
```

Unrelated to this PR.
- Addressed separately in #19

**Review by sethkfman — APPROVED** [review]
LGTM

**Pull request merged**
