### PR TITLE
devDeps: appium@^1.22.3->^2.5.4

### PR DESCRIPTION
**Pull request by legobeat**
Bump appium to latest.

#### Blocked by
- [x] #27
  - [x] #26

### CODE REVIEW

**Comment by legobeat** [comment]
@SocketSecurity ignore npm/appium@2.5.4

shell access, install scripts ok

**Comment by legobeat** [comment]
@SocketSecurity ignore npm/foreground-child@3.1.1
    @SocketSecurity ignore npm/detect-libc@2.0.3

shell access ok

**Comment by legobeat** [comment]
@SocketSecurity ignore npm/spdy@4.0.2

network access ok

**Comment by legobeat** [comment]
@SocketSecurity ignore npm/@appium/base-driver@9.6.0

network access ok

**Comment by legobeat** [comment]
@SocketSecurity ignore npm/sharp@0.33.3

install scripts ok

**Review by sethkfman — APPROVED** [review]
LGTM

**Pull request merged**
