### PR TITLE
devDeps: appium@1.17.0->^1.22.3

### PR DESCRIPTION
**Pull request by legobeat**
Bump appium to latest 1.x.

#### Blocked by
- [x] #26

### CODE REVIEW

**Comment by legobeat** [comment]
@SocketSecurity ignore npm/appium-remote-debugger@8.13.2
    @SocketSecurity ignore npm/asyncbox@2.9.4

new author ok

**Comment by legobeat** [comment]
@SocketSecurity ignore npm/appium-flutter-driver@0.0.36

network access ok

**Comment by legobeat** [comment]
@SocketSecurity ignore npm/utf-8-validate@5.0.10
    @SocketSecurity ignore npm/appium-geckodriver@0.3.3
    @SocketSecurity ignore npm/appium-mac2-driver@0.14.1
    @SocketSecurity ignore npm/appium-safari-driver@2.2.1

shell access ok

**Comment by legobeat** [comment]
@SocketSecurity ignore npm/utf-8-validate@5.0.10

native code ok

**Comment by legobeat** [comment]
@SocketSecurity ignore npm/bufferutil@4.0.8

native code ok

**Comment by legobeat** [comment]
@SocketSecurity ignore npm/@dabh/colors@1.4.0


known legacy; will be resolved when upgrading to appium v2

**Review by leotm — APPROVED** [review]

**Pull request merged**
